### ISSUE TITLE
Temporary files error

### ISSUE THREAD

**Issue by norkunas** [rosstuck/TuckConverterBundle#13]
In windows i encountered temporary files unlinking error because of permissions. I think it would be better to suppress `unlink` errors because it's not so important if the conversion succeeds.

**Comment by rosstuck** [comment]
It's a fair point but after some thought, I've decided to keep it for now for two reasons:
- I want to get alerted on the web UI version of these errors since silencing them could mean I get uploaded files from people's app left in my temp directory (which I don't want the responsibility for)
- General aversion to suppressing errors.

Thanks for digging in though, I really appreciate it. :smiley:
