### ISSUE TITLE
Converting config from fos_user doesn't work

### ISSUE THREAD

**Issue by matthiaskrieft** [rosstuck/TuckConverterBundle#17]
I tried this xml with the web-ui-converter:
https://raw.githubusercontent.com/FriendsOfSymfony/FOSUserBundle/master/Resources/config/validation.xml

Didn't work unfortunately. Any hint?

**Comment by rosstuck** [comment]
Hi Matthias!

This appears to be a validator mapping. Unfortunately, this tool only
supports service container config files. Sorry!

On Oct 13, 2017 1:56 PM, "Matthias Krieft" <notifications@github.com> wrote:

I tried this xml with the web-ui-converter:
https://raw.githubusercontent.com/FriendsOfSymfony/FOSUserBundle/master/
Resources/config/validation.xml

Didn't work unfortunately. Any hint?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rosstuck/TuckConverterBundle/issues/17>, or mute the
thread

**Comment by matthiaskrieft** [comment]
Ah ok, thx anyway for the quick response! :-)
