### ISSUE TITLE
Service not converting..

### ISSUE THREAD

**Issue by menzow** [rosstuck/TuckConverterBundle#5]
Hello,

I would like to (what I think is) a bug.

I have this service XML:
```
<service id="sonata.admin.comment" class="%sonata.admin.comment.class%">
    <tag name="sonata.admin" manager_type="orm" group="sonata_blog" label="comments"
        label_catalogue="%sonata.admin.comment.translation_domain%"
        label_translator_strategy="sonata.admin.label.strategy.underscore" />
    <argument />
    <argument>%sonata.admin.comment.entity%</argument>
    <argument>%sonata.admin.comment.controller%</argument>

    <call method="setTemplates">
        <argument type="collection">
            <argument key="inner_list_row">
                YourNSYourBundle:Admin:inner_row_comment.html.twig
            </argument>
            <argument key="base_list_field">
                SonataAdminBundle:CRUD:base_list_flat_field.html.twig
            </argument>
        </argument>
    </call>
</service>
```

It runs perfectly in symfony. But when I try to convert it to YML , the converter says it is invalid.

How and why is this happening?

**Comment by rosstuck** [comment]
Okay, the holidays are finally over so I had some time to dig into this.

There's two issues here:

1. The extra line endings when going from XML to YAML. This is an upstream issue in Symfony but it's been closed there as wontfix. I agree with them because it's impossible to know if the newlines are meant to be part of the value or not. Therefore, I won't try to work around this either and just have to recommend that folks put the xml argument tags on the sameline as the argument value.
2. There's no real error messages to help folks when they don't paste in a complete file or use invalid snippets. This seems to be coming mostly from XML input so I've added some quick'n'dirty error checks to the ConverterSite JS code. I probably won't implement these in the converter bundle itself since those just take the source files, which pretty much eliminates the chance of copy and paste error. I'm hoping this'll prevent folks from having the same issues you did.

Thanks again for taking the time to report this and dig into the issue, it's much appreciated! :smiley:
